"""add_ticket_links_table

Revision ID: c76dbb3346da
Revises: 47b1204c683c
Create Date: 2026-02-14 15:40:48.376606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76dbb3346da'
down_revision: Union[str, None] = '47b1204c683c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ticket_id', sa.Integer(), nullable=False),
    sa.Column('target_ticket_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_links_id'), 'ticket_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_links_id'), table_name='ticket_links')
    op.drop_table('ticket_links')
    # ### end Alembic commands ###
